services:
  frontend:
    # build:
    #   context: ./frontend/.
    image: sourabhlodhi/chattingo-frontend:latest
    container_name: frontend
    networks:
      - chattingo-app
    depends_on:
      - backend
    ports: 
      - "3000:80"
    
  backend:
    # build:
    #   context: ./backend/.
    image: sourabhlodhi/chattingo-backend:latest
    container_name: backend
    networks:
      - chattingo-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/chattingo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: 9b4893a8ba233b4ae235718e5f813dbb1a5d9217b899c51168fedf222258b70b 
    ports:
      - "8080:8080"
    depends_on:
      mysql: 
        condition: service_healthy
    restart: always
    
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - chattingo-app
    volumes:
      - springboot_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chattingo_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s
     
volumes:
  springboot_data:
    name: springboot_data

networks:
  chattingo-app:
    name: chattingo-app
